ETicaret.Web/Areas/AdminPanel/Controllers/FotograflarController.cs
using AutoMapper;
using ETicaret.Core.DTO;
using ETicaret.Core.ETicaretDatabase;
using ETicaret.Core.IService;
using Microsoft.AspNetCore.Mvc;

namespace ETicaret.Web.Areas.AdminPanel.Controllers
{
    public class FotograflarController : Controller
    {
        private readonly IUrunlerService _urunlerService;
        private readonly IFotograflarService _fotograflarService;
        private readonly IMapper _mapper;

        public FotograflarController(IUrunlerService urunler, IFotograflarService service, IMapper mapper)
        {
            _urunlerService = urunler;
            _fotograflarService = service;
            _mapper = mapper;
        }

        public async Task<IActionResult> FotograflarIndex()
        {
            var fotograflar = await _fotograflarService.GetFotografWithUrunAsync();
            return View(fotograflar);
        }

        public async Task<IActionResult> FotografEkleIndex()
        {
            var urunlerList = await _urunlerService.GetAllAsyncs();
            var urunlerDTO = _mapper.Map<List<UrunlerUpdateDTO>>(urunlerList);
            ViewBag.urunler = urunlerDTO;

            var fotograflar = await _fotograflarService.GetAllAsyncs();
            var fotograflarDTO = _mapper.Map<List<FotografGuncelleDTO>>(fotograflar);
            ViewBag.fotograflar = fotograflarDTO;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FotografEkleIndex(Fotograflar fotograf)
        {
            fotograf.EklenmeTarih = DateTime.Now;
            fotograf.AktifMi = true;
            var sonuc = await _fotograflarService.AddAsync(fotograf);

            if (sonuc != null)
            {
                return RedirectToAction("FotograflarIndex");
            }

            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> Upload(IFormFile file)
        //{
        //    var uploads = @"C:\UrunResimleri\";
        //    if (file.Length > 0)
        //    {
        //        var filePath = Path.Combine(uploads, file.FileName);

        //        ViewData["dosyaYolu"] = filePath.ToString();

        //        using (var fileStream = new FileStream(filePath, FileMode.Create))
        //        {
        //            await file.CopyToAsync(fileStream);
        //        }

        //        // Return the file path in JSON format
        //        return Json(new { success = true, filePath = filePath });
        //    }

        //    return Json(new { success = false });
        //}

        public async Task<IActionResult> FotografGuncelleIndex(int id)
        {
            var getirFotograf = await _fotograflarService.GetFotografWithUrunAsync(id);
            var urunList = await _urunlerService.GetAllAsyncs();

            var urunler = urunList.ToList();
            var fotograf = getirFotograf;

            var model = new Tuple<List<Urunler>, GetFotograflarWithUrunlerDTO>(urunler, fotograf);

            var fotograflar = await _fotograflarService.GetAllAsyncs();
            var fotograflarDTO = _mapper.Map<List<FotografGuncelleDTO>>(fotograflar);
            ViewBag.fotograflar = fotograflarDTO;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> FotografGuncelleIndex(Fotograflar fotograf)
        {
            if (ModelState.IsValid)
            {
                fotograf.GuncellenmeTarih = DateTime.Now;
                await _fotograflarService.UpdateAsync(_mapper.Map<Fotograflar>(fotograf));
                TempData["guncellemeMesaj"] = "<b>Güncelleme başarılı.</b>";
                return RedirectToAction("FotograflarIndex");
            }

            TempData["hataMesaj"] = "<b>Güncelleme hata verdi, lütfen kontrol ediniz.</b>";

            return RedirectToAction("FotografGuncelleIndex", fotograf.Id);
        }

        public async Task<IActionResult> FotografSilIndex(int id)
        {
            var fotograf = await _fotograflarService.GetByIdAsync(id);

            return View(fotograf);
        }

        [HttpPost, ActionName("FotografSilIndex")]
        public async Task<IActionResult> FotografSilIndex(int id, bool aktifMi)
        {
            var fotograf = await _fotograflarService.GetByIdAsync(id);

            if (ModelState.IsValid)
            {
                await _fotograflarService.RemoveAsync(_mapper.Map<Fotograflar>(fotograf));
                TempData["guncellemeMesaj"] = "<b>Silme başarılı.</b>";

                return RedirectToAction("FotograflarIndex");
            }

            TempData["hataMesaj"] = "<b>Silme hata verdi, lütfen kontrol ediniz.</b>";

            return RedirectToAction("FotografSilIndex", fotograf.Id);
        }


    }
}

ETicaret.Web/Areas/AdminPanel/Views/Fotograflar/FotografEkleIndex.cshtml
@{
    ViewData["Title"] = "FotografEkleIndex";

}

@section addTopLibrary {
    <link href="~/AdminLTE/plugins/dropzone/dropzone.css" rel="stylesheet" />
    <link href="~/AdminLTE/plugins/dropzone/min/dropzone.min.css" rel="stylesheet" />
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="~/AdminPanel/Fotograflar/FotografEkleIndex">Fotoğraf Ekle</a></li>
                    <li class="breadcrumb-item"><a href="~/AdminPanel/Fotograflar/FotograflarIndex">Fotoğraf Listesi</a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- jquery validation -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Fotoğraf Ekle</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form asp-action="FotografEkleIndex" id="fotografEkleIndex" asp-controller="Fotograflar" method="post">

                        <div class="card-body">

                            <div class="form-group">
                                <label asp-for="fotografAciklamasi">Fotoğraf Açıklaması</label>
                                <input name="fotografAciklamasi" asp-for="fotografAciklamasi" type="text" class="form-control" placeholder="Fotoğraf Açıklaması">
                                <span asp-validation-for="fotografAciklamasi" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="FotografYolu">Fotoğraf Yolu</label>
                                <input name="FotografYolu" asp-for="FotografYolu" type="text" class="form-control" id="dosyaYolu" placeholder="Fotoğraf Yolu" value="">
                                <span asp-validation-for="FotografYolu" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="fotografSirasi">Fotoğraf Sırası</label>
                                <input name="fotografSirasi" asp-for="fotografSirasi" type="text" class="form-control" placeholder="Fotoğraf Sırası">
                                <span asp-validation-for="fotografSirasi" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="urunId">Ürün ID.</label>
                                <input name="urunId" asp-for="urunId" type="text" class="form-control" placeholder="Ürün ID.">
                                <span asp-validation-for="urunId" class="text-danger"></span>
                            </div>

                        </div>

                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-success" value="Fotoğraf Ekle" />
                        </div>

                        <div>
                            @Html.Raw(ViewBag.mesaj)
                        </div>
                    </form>

                    <div class="col-md-12">
                        <div id="dropzone">
                            <form action="/Fotograflar/Upload" class="dropzone needsclick dz-clickable" id="uploader">
                                <div class="dz-message needsclick">
                                    Fotoğrafı sürükleyip bırakın veya buraya tıklayın.<br>
                                </div>
                            </form>
                        </div>
                    </div>

                    <br />

                    <div class="d-flex justify-content-center">
                        <button type="button" class="btn btn-danger" id="fotografDegistir">Fotoğraf Değiştir</button>
                    </div>

                    <br />

                </div>
            </div>
        </div>
    </div>
</section>

@section addBottomLibrary {

    <script src="~/AdminLTE/plugins/jquery-validation/jquery.validate.js"></script>

    <script>
        $(function () {

            $('#fotografEkleIndex').validate({
                rules: {
                    makaleKategori: {
                        required: true
                    },
                    makaleBaslik: {
                        required: true
                    },
                    makaleIcerik: {
                        required: true
                    }

                },
                messages: {
                    makaleKategori: {
                        required: "Makale Kategori alanı zorunludur"
                    },
                    makaleBaslik: {
                        required: "Başlık alanı zorunludur"
                    },
                    makaleIcerik: {
                        required: "Makale İçerik alanı zorunludur"
                    }
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });

    </script>

    <script src="~/AdminLTE/plugins/dropzone/dropzone.js"></script>
    <script src="~/AdminLTE/plugins/dropzone/min/dropzone.min.js"></script>

    <script>

        var myDropzone = new Dropzone("#uploader", {
            dictDefaultMessage: "Yüklenecek dosyaları buraya sürükleyin veya tıklayın.",
            maxFiles: 1, // Maksimum dosya sayısı
            maxFilesize: 2, // MB cinsinden maksimum dosya boyutu
            acceptedFiles: ".jpeg,.jpg,.png,.gif", // Kabul edilen dosya türleri
            init: function () {
                this.on("addedfile", function (file) {

                    // Dosya boyutu kontrolü
                    if (file.size > 2097152) { // 2 MB
                        this.removeFile(file);
                        alert("Dosya boyutu 2 MB'ı geçemez.");
                        return false;
                    }

                    // Dosya sayısı kontrolü
                    if (this.files.length > 1) {
                        alert("Yalnızca 1 dosya yükleyebilirsiniz.");
                        this.removeFile(this.files[1]);
                        return false;
                    }

                    // Dosya türü kontrolü
                    var acceptedFileTypes = ["image/jpeg", "image/jpg", "image/png", "image/gif"];
                    if (!acceptedFileTypes.includes(file.type)) {
                        this.removeFile(file);
                        alert("Yalnızca resim dosyaları yükleyebilirsiniz.");
                        return false;
                    }

                    // Dosya yükleme başarılı olduğunda
                    this.on("success", function (file, response) {
                        // response içinde controller'dan gelen veriler bulunur
                        if (response.success) {
                            // Dosya yolu input elemanına değeri ekle
                            document.getElementById("dosyaYolu").value = response.filePath;
                        }
                    });
                });

            }
        });

        document.getElementById("fotografDegistir").addEventListener("click", function () {
            // Mevcut dosyayı kaldır
            myDropzone.removeAllFiles();

        });

    </script>
}

ETicaret.Web/Areas/AdminPanel/Views/Fotograflar/FotografGuncelleIndex.cshtml
@using ETicaret.Core.ETicaretDatabase
@using ETicaret.Core.DTO

@model Tuple<List<Urunler>, GetFotograflarWithUrunlerDTO>

@{
    ViewData["Title"] = "FotografGuncelleIndex";
}

@section addTopLibrary {
    <link href="~/AdminLTE/plugins/dropzone/dropzone.css" rel="stylesheet" />
    <link href="~/AdminLTE/plugins/dropzone/dropzone.min.css" rel="stylesheet" />
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="~/AdminPanel/Fotograflar/FotografGuncelleIndex/#">Fotoğraf Güncelle</a></li>
                    <li class="breadcrumb-item"><a href="~/AdminPanel/Fotograflar/FotograflarIndex">Fotoğraf Listesi</a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- jquery validation -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Fotoğraf Güncelle</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form asp-action="FotografGuncelleIndex" id="fotografGuncelleIndex" asp-controller="Fotograflar" method="post">

                        <div class="card-body">

                            <div class="form-group">
                                <label asp-for="fotografAciklamasi">Fotoğraf Açıklaması</label>
                                <input name="fotografAciklamasi" asp-for="fotografAciklamasi" type="text" class="form-control" value="@Model.Item2.FotografAciklamasi" placeholder="Fotoğraf Açıklaması">
                                <span asp-validation-for="fotografAciklamasi" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="FotografYolu">Fotoğraf Yolu</label>
                                <input name="FotografYolu" asp-for="FotografYolu" type="text" class="form-control" id="dosyaYolu" value="@Model.Item2.FotografYolu" placeholder="Fotoğraf Yolu">
                                <span asp-validation-for="FotografYolu" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="fotografSirasi">Fotoğraf Sırası</label>
                                <input name="fotografSirasi" asp-for="fotografSirasi" type="text" class="form-control" value="@Model.Item2.FotografSirasi" placeholder="Fotoğraf Sırası">
                                <span asp-validation-for="fotografSirasi" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="urunId">Ürün ID.</label>
                                <input name="urunId" asp-for="urunId" type="number" class="form-control" value="@Model.Item2.UrunId" placeholder="Ürün ID.">
                                <span asp-validation-for="urunId" class="text-danger"></span>
                            </div>

                        </div>

                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-warning" value="Fotoğraf Güncelle" />
                        </div>
                        <div>
                            @Html.Raw(TempData["hataMesaji"])
                        </div>
                    </form>

                    <div class="col-md-12">
                        <div id="dropzone">
                            <form action="/Fotograflar/Upload" class="dropzone needsclick dz-clickable" id="uploader">
                                <div class="dz-message needsclick">
                                    Fotoğrafı sürükleyip bırakın veya buraya tıklayın.<br>
                                </div>
                            </form>
                        </div>
                    </div>

                    <br />

                    <div class="d-flex justify-content-center">
                        <button type="button" class="btn btn-danger" id="fotografDegistir">Fotoğraf Değiştir</button>
                    </div>

                    <br />

                </div>
            </div>
        </div>
    </div>
</section>

@section addBottomLibrary {

    <script src="~/AdminLTE/plugins/jquery-validation/jquery.validate.js"></script>
    <script>
        $(function () {

            $('#urunKeydetIndex').validate({
                rules: {
                    makaleKategori: {
                        required: true
                    },
                    makaleBaslik: {
                        required: true
                    },
                    makaleIcerik: {
                        required: true
                    }

                },
                messages: {
                    makaleKategori: {
                        required: "Makale Kategori alanı zorunludur"
                    },
                    makaleBaslik: {
                        required: "Başlık alanı zorunludur"
                    },
                    makaleIcerik: {
                        required: "Makale İçerik alanı zorunludur"
                    }
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });

    </script>

    <script src="~/AdminLTE/plugins/dropzone/dropzone.js"></script>
    <script src="~/AdminLTE/plugins/dropzone/min/dropzone.min.js"></script>

    <script>

        var myDropzone = new Dropzone("#uploader", {
            dictDefaultMessage: "Yüklenecek dosyaları buraya sürükleyin veya tıklayın.",
            maxFiles: 1, // Maksimum dosya sayısı
            maxFilesize: 2, // MB cinsinden maksimum dosya boyutu
            acceptedFiles: ".jpeg,.jpg,.png,.gif", // Kabul edilen dosya türleri
            init: function () {
                this.on("addedfile", function (file) {

                    // Dosya boyutu kontrolü
                    if (file.size > 2097152) { // 2 MB
                        this.removeFile(file);
                        alert("Dosya boyutu 2 MB'ı geçemez.");
                        return false;
                    }

                    // Dosya sayısı kontrolü
                    if (this.files.length > 1) {
                        alert("Yalnızca 1 dosya yükleyebilirsiniz.");
                        this.removeFile(this.files[1]);
                        return false;
                    }

                    // Dosya türü kontrolü
                    var acceptedFileTypes = ["image/jpeg", "image/jpg", "image/png", "image/gif"];
                    if (!acceptedFileTypes.includes(file.type)) {
                        this.removeFile(file);
                        alert("Yalnızca resim dosyaları yükleyebilirsiniz.");
                        return false;
                    }

                    // Dosya yükleme başarılı olduğunda
                    this.on("success", function (file, response) {
                        // response içinde controller'dan gelen veriler bulunur
                        if (response.success) {
                            // Dosya yolu input elemanına değeri ekle
                            document.getElementById("dosyaYolu").value = response.filePath;
                        }
                    });
                });

            }
        });

        document.getElementById("fotografDegistir").addEventListener("click", function () {
            // Mevcut dosyayı kaldır
            myDropzone.removeAllFiles();

        });

    </script>

}

ETicaret.Web/Areas/AdminPanel/Views/Fotograflar/FotografSilIndex.cshtml
@using ETicaret.Core.ETicaretDatabase

@model Fotograflar

@{
    ViewData["Title"] = "FotografSilIndex";
    
}


<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="~/AdminPanel/Fotograflar/FotografSilIndex/#">Fotoğraf Sil</a></li>
                    <li class="breadcrumb-item"><a href="~/AdminPanel/Fotograflar/FotograflarIndex">Fotoğraf Listesi</a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- jquery validation -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Fotoğraf Sil</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form asp-action="FotografSilIndex" id="fotografSilIndex" asp-controller="Fotograflar" method="post">

                        <div class="form-group" style="margin:30px 0px 30px 30px">
                            @Html.LabelFor(model => model.AktifMi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.AktifMi)
                                    @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-danger" value="Fotoğraf Sil" />
                        </div>
                        <div>
                            @Html.Raw(TempData["hataMesaji"])
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section addBottomLibrary {

    <script src="~/AdminLTE/plugins/jquery-validation/jquery.validate.js"></script>
}

ETicaret.Web/Areas/AdminPanel/Views/Fotograflar/FotograflarIndex.cshtml
@using ETicaret.Core.DTO

@model List<GetFotograflarWithUrunlerDTO>

@{
    ViewData["Title"] = "FotograflarIndex";
    
}

@section addTopLibrary {

    <!-- DataTables -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">
                    <a href='~/AdminPanel/Fotograflar/FotografEkleIndex' class='btn btn-block btn-success col-md-3'>Yeni Fotoğraf Ekle</a>
                </h1>
            </div><!-- /.col -->

            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="~/AdminPanel/Fotograflar/FotograflarIndex">Fotoğraflar</a></li>
                    <li class="breadcrumb-item"><a href="~/AdminPanel/AdminAnasayfa/AdminAnasayfaIndex">Admin Panel</a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>ID.</th>
                                    <th>FOTOĞRAF AÇIKLAMASI</th>
                                    <th>FOTOĞRAF YOLU</th>
                                    <th>FOTOĞRAF SIRASI</th>
                                    <th>ÜRÜN ID.</th>
                                    <th>AKTİF Mİ</th>
                                    <th>EKLENME TARİHİ</th>
                                    <th>GÜNCELLE</th>
                                    <th>FOTO. SİL</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>

                                        <td>@item.FotografAciklamasi</td>

                                        <td>@item.FotografYolu</td>

                                        <td>@item.FotografSirasi</td>

                                        <td>@item.UrunId</td>

                                        <td>
                                            @{
                                                string durum = item.AktifMi == true ? "EVET" : "HAYIR";
                                            }
                                            @durum
                                            </td>

                                        <td>@item.EklenmeTarih</td>

                                        <td>
                                            <a href='~/AdminPanel/Fotograflar/FotografGuncelleIndex/@item.Id' class='btn btn-sm btn-warning' style="width:100%;"><i class='fas fa-pencil-alt'></i></a>
                                        </td>

                                        <td>
                                            <a href='~/AdminPanel/Fotograflar/FotografSilIndex/@item.Id' class='btn btn-sm btn-danger' style="width:100%;"><i class='fas fas fa-trash'></i></a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        
        <div>
            @Html.Raw(TempData["guncellemeMesaj"])
        </div>

    </div>
</section>

@section addBottomLibrary {

    <script src="~/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/AdminLTE/plugins/jszip/jszip.min.js"></script>
    <script src="~/AdminLTE/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/AdminLTE/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="~/AdminLTE/dist/js/adminlte.min.js"></script>
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": [
                    "copy",
                    // "csv",
                    "excel",
                    "pdf",
                    "print",
                    "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
        </script>
}