ETicaret.Web/Areas/AdminPanel/Controllers/YorumlarController.cs
using AutoMapper;
using ETicaret.Core.DTO;
using ETicaret.Core.ETicaretDatabase;
using ETicaret.Core.IService;
using Microsoft.AspNetCore.Mvc;

namespace ETicaret.Web.Areas.AdminPanel.Controllers
{
    public class YorumlarController : Controller
    {
        private readonly IYorumlarService _service;
        private readonly IKullanicilarService _kullanicilarService;
        private readonly IUrunlerService _urunlerService;
        private readonly IMapper _mapper;


        public YorumlarController(IYorumlarService service, IKullanicilarService kullanicilarService, IUrunlerService urunlerService,IMapper mapper)
        {
            _service = service;
            _kullanicilarService = kullanicilarService;
            _urunlerService = urunlerService;
            _mapper = mapper;
        }

        public async Task<IActionResult> YorumlarIndex()
        {
            var yorumlar = await _service.GetYorumlarWithKullanicilarAsync();
            return View(yorumlar);
        }

        public async Task<IActionResult> YorumEkleIndex()
        {
            var yorumList = await _service.GetAllAsyncs();
            var sonuc = _mapper.Map<List<YorumlarDTO>>(yorumList);
            ViewBag.yorumlar = sonuc;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> YorumEkleIndex(Yorumlar yorumlar)
        {
            if (ModelState.IsValid)
            {
                var sonuc = await _service.AddAsync(yorumlar);
                if (sonuc != null)
                {
                    return RedirectToAction("YorumlarIndex");
                }
            }
            var yorumList = await _service.GetAllAsyncs();
            var yorumDTO = _mapper.Map<List<YorumlarDTO>>(yorumList);
            ViewBag.yorumlar = yorumDTO;

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> YorumGuncelleIndex(int Id)
        {
            var getirYorumKullanici = await _service.GetYorumlarWithKullanicilarAsync(Id);
            //var getirYorumUrun = await _service.GetYorumlarWithUrunlerAsync(Id);
            var model = getirYorumKullanici;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> YorumGuncelleIndex(Yorumlar yorumlar)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(_mapper.Map<Yorumlar>(yorumlar));
                TempData["guncellemeMesaj"] = "<b>Güncelleme başarılı</b>";
                return RedirectToAction("YorumlarIndex");
            }

            TempData["hataMesaji"] = "<b>Güncelleme hata verdi, lütfen kontrol ediniz </b>";

            return RedirectToAction("YorumlarIndex", yorumlar.Id);
        }

        [HttpGet]
        public async Task<IActionResult> YorumSilIndex(int Id)
        {
            var yorum = await _service.GetByIdAsync(Id);
            return View(yorum);
        }

        [HttpPost, ActionName("YorumSilIndex")]
        public async Task<IActionResult> YorumSilIndex(int Id, bool aktifMi)
        {
            var yorum = await _service.GetByIdAsync(Id);
            if (ModelState.IsValid)
            {
                await _service.RemoveAsync(_mapper.Map<Yorumlar>(yorum));
                TempData["guncellemeMesaj"] = "<b>Silme başarılı</b>";
                return RedirectToAction("YorumlarIndex");
            }
            TempData["hataMesaji"] = "<b>Silme hata verdi, lütfen kontrol ediniz </b>";

            return RedirectToAction("YorumSilIndex", yorum.Id);
        }

        

    }
}

ETicaret.Web/Areas/AdminPanel/Views/Yorumlar/YorumEkleIndex.cshtml
@using ETicaret.Core.DTO
@model GetYorumlarWithKullanicilarDTO

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/AdminPanel/Yorumlar/YorumlarIndex">Yorum Listesi</a></li>
                    <li class="breadcrumb-item active">Yorum Ekle</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- jquery validation -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">YORUM EKLE</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form asp-action="YorumEkleIndex" id="yorumEkleIndex" asp-controller="Yorumlar" method="post">

                        <div class="card-body">

                            <div class="form-group">
                                <label asp-for="UrunId">Urun Id</label>
                                <input name="UrunId" asp-for="UrunId" type="text" class="form-control" placeholder="UrunId">
                                <span asp-validation-for="UrunId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="KullaniciId">Kullanıcı Id</label>
                                <input name="KullaniciId" asp-for="KullaniciId" type="text" class="form-control" placeholder="KullaniciId">
                                <span asp-validation-for="KullaniciId" class="text-danger"></span>
                            </div>
                            @* <div class="form-group">
                                <label asp-for="Email">Email</label>
                                <input name="Email" asp-for="Email" type="text" class="form-control" placeholder="Email">
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div> *@

                            <div class="form-group">
                                <label asp-for="YorumUstId">YorumUstId</label>
                                <input name="YorumUstId" asp-for="YorumUstId" type="text" class="form-control" placeholder="YorumUstId">
                                <span asp-validation-for="YorumUstId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Yorum">Yorum</label>
                                <input name="Yorum" asp-for="Yorum" type="text" class="form-control" placeholder="Yorum">
                                <span asp-validation-for="Yorum" class="text-danger"></span>
                            </div>



                        </div>

                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-success" value="Yorum Ekle" />
                        </div>
                        <div>
                            @Html.Raw(ViewBag.mesaj)
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section addBottomLibrary {

    <script src="~/AdminLTE/plugins/jquery-validation/jquery.validate.js"></script>
    <script>
        $(function () {

            $('#yorumEkleIndex').validate({
                rules: {
                    Adi: {
                        required: true
                    },
                    Soyadi: {
                        required: true
                    },
                    Email: {
                        required: true
                    },
                    YorumUstId: {
                        required: true
                    },
                    Yorum: {
                        required: true
                    }

                },
                messages: {
                    Adi: {
                        required: "Adi alanı zorunludur"
                    },
                    Soyadi: {
                        required: "Soyadi alanı zorunludur"
                    },
                    Email: {
                        required: "Email İçerik alanı zorunludur"
                    },
                    YorumUstId: {
                        required: "YorumustId İçerik alanı zorunludur"
                    },
                    Yorum: {
                        required: "Yorum İçerik alanı zorunludur"
                    }
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });

    </script>
}

ETicaret.Web/Areas/AdminPanel/Views/Yorumlar/YorumGuncelleIndex.cshtml
@using ETicaret.Core.ETicaretDatabase
@using ETicaret.Core.DTO

@model GetYorumlarWithKullanicilarDTO
@* @model Tuple<List<Kategoriler>,GetUrunlerWithKategoriDTO> *@

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/AdminPanel/Yorumlar/YorumlarIndex">Yorum Listesi</a></li>
                    <li class="breadcrumb-item active">Ürün Güncelle</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- jquery validation -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">YORUM GÜNCELLE</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form asp-action="YorumGuncelleIndex" asp-controller="Yorumlar" method="post">

                        <div class="card-body">
                            <div class="form-group">
                                <label asp-for="UrunId">Urun Id</label>
                                <input name="UrunId" asp-for="UrunId" type="text" value="@Model.UrunId" class="form-control" placeholder="UrunId">
                                <span asp-validation-for="UrunId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="KullaniciId">Kullanıcı ID</label>
                                <input name="KullaniciId" asp-for="KullaniciId" value="@Model.KullaniciId" type="text" class="form-control" placeholder="KullaniciId">
                                <span asp-validation-for="Adi" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="YorumUstId">YorumUstId</label>
                                <input name="YorumUstId" asp-for="YorumUstId" value="@Model.YorumUstId" type="text" class="form-control" placeholder="YorumUstId">
                                <span asp-validation-for="YorumUstId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Yorum">Yorum</label>
                                <input name="Yorum" asp-for="Yorum" value="@Model.Yorum" type="text" class="form-control" placeholder="Yorum">
                                <span asp-validation-for="Yorum" class="text-danger"></span>
                            </div>



                        </div>

                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-warning" value="Yorum Güncelle" />
                        </div>
                        <div>
                            @Html.Raw(TempData["hataMesaji"])
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section addBottomLibrary {

    <script src="~/AdminLTE/plugins/jquery-validation/jquery.validate.js"></script>
    <script>
        $(function () {

            $('#urunKeydetIndex').validate({
                rules: {
                    makaleKategori: {
                        required: true
                    },
                    makaleBaslik: {
                        required: true
                    },
                    makaleIcerik: {
                        required: true
                    }

                },
                messages: {
                    makaleKategori: {
                        required: "Makale Kategori alanı zorunludur"
                    },
                    makaleBaslik: {
                        required: "Başlık alanı zorunludur"
                    },
                    makaleIcerik: {
                        required: "Makale İçerik alanı zorunludur"
                    }
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });

    </script>
}

ETicaret.Web/Areas/AdminPanel/Views/Yorumlar/YorumSilIndex.cshtml
@using ETicaret.Core.ETicaretDatabase

@model Yorumlar

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/AdminPanel/Yorumlar/YorumlarIndex">Yorum Listesi</a></li>
                    <li class="breadcrumb-item active">Yorum Sil</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- jquery validation -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Yorum Sil</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form asp-action="YorumSilIndex" id="yorumSilIndex" asp-controller="Yorumlar" method="post">

                        @* <div class="form-group" style="margin:30px 0px 30px 30px">
                            @Html.LabelFor(model => model.AktifMi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.AktifMi)
                                    @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div> *@

                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-danger" value="Yorum Sil" />
                        </div>
                        <div>
                            @Html.Raw(TempData["hataMesaji"])
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@section addBottomLibrary {

    <script src="~/AdminLTE/plugins/jquery-validation/jquery.validate.js"></script>
}

ETicaret.Web/Areas/AdminPanel/Views/Yorumlar/YorumlarIndex.cshtml
@using ETicaret.Core.DTO

@model List<GetYorumlarWithKullanicilarDTO>
@* @model List<GetYorumlarWithUrunlerDTO> *@

@section addTopLibrary {

    <!-- DataTables -->
    <link rel="stylesheet" href="~/AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/AdminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
}

@* @{
    ViewData["Title"] = "YorumlarIndex";
    Layout = "~/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml";
} *@

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">
                    <a href="~/AdminPanel/Yorumlar/YorumEkleIndex" class="btn btn-success">Yeni Yorum Ekle</a>
                </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">

                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Yorumlar</a></li>
                    <li class="breadcrumb-item active">Yorumlar Listesi</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body ">

                        <table class="table table-bordered">
                            <tr>
                                <th>Yorum ID</th>
                                <th>Yorum</th>
                                <th>Yorum Tarihi</th>
                                <th>Yorum Üst ID</th>
                                <th>Ürün Id</th>
                                @* <th>Ürün Adı</th> *@
                                <th>Kullanıcı ID</th>
                                <th>AKTİF Mİ</th>
                                <th>Adi</th>
                                <th>Soyadi</th>
                                <th>E-Mail</th>
                                <th>Güncelle</th>
                                <th>Sil</th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Yorum</td>
                                    <td>@item.EklenmeTarih</td>
                                    <td>@item.YorumUstId</td>
                                    <td>@item.UrunId</td>
                                    @* <td>@item.Urunler.UrunAdi</td> *@
                                    <td>@item.KullaniciId</td>
                                    <td>
                                        @{
                                            string durum = item.AktifMi == true ? "EVET" : "HAYIR";
                                        }
                                        @durum
                                    </td>
                                    <td>@item.Kullanicilar.Adi</td>
                                    <td>@item.Kullanicilar.Soyadi</td>
                                    <td>@item.Kullanicilar.KullaniciEmail</td>
                                    <td>

                                        <a href='~/AdminPanel/Yorumlar/YorumGuncelleIndex/@item.Id' class='btn btn-sm btn-warning'><i class='fas fa-pencil-alt'></i></a>
                                    </td>
                                    <td>
                                        <a href='~/AdminPanel/Yorumlar/YorumSilIndex/@item.Id' class='btn btn-sm btn-danger'><i class='fas fa-pencil-alt'></i></a>
                                    </td>
                                </tr>
                            }
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>